name: Continuos Integration

# on: [pull_request, push, issues, issue_comment]
# on: push
on: 
  pull_request:
    branches: [ "main" ]

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Hello World !!!
      run: echo "Hello World !!!"
    - name: Print IPv4 # Some random command
      run: ifconfig -a
    - name: curl www.globo.com
      run: |
        sudo apt-get update
        sudo apt-get install curl
        curl -I https://www.globo.com
    - name: Número randômico    
      run: echo $RANDOM
    - name: Data de hoje
      run: date
